# Generated by Django 4.2.5 on 2023-09-22 01:27

import core.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=functools.partial(
                    core.utils._update_filename,
                    *(),
                    **{"hash": True, "path": "avatars"}
                ),
                verbose_name="프로필 사진",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=20, verbose_name="닉네임"),
        ),
    ]
