<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-14 07:43
=======
# Generated by Django 4.2.5 on 2023-10-03 09:59
>>>>>>> 7529f760ceef635efcdabf57515a499c8a3b1429

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name="user",
            options={"verbose_name_plural": "회원 목록"},
=======
            name='user',
            options={'verbose_name_plural': '회원 목록'},
>>>>>>> 7529f760ceef635efcdabf57515a499c8a3b1429
        ),
    ]
