# Generated by Django 4.2.5 on 2023-10-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("room", "0002_alter_room_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendee",
            options={"verbose_name_plural": "참가자 목록"},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name_plural": "투표 목록"},
        ),
        migrations.AlterField(
            model_name="room",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="방장",
            ),
        ),
    ]
