# Generated by Django 4.2.5 on 2023-10-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_remove_roomcode_created_at"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="room",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="room.room"
            ),
            preserve_default=False,
        ),
    ]
