# Generated by Django 4.2.5 on 2023-10-20 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
